-- Temporarily disable RLS for testing
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE presentations DISABLE ROW LEVEL SECURITY;
ALTER TABLE slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE presentation_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE presentation_shares DISABLE ROW LEVEL SECURITY;
ALTER TABLE presentation_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE template_slides DISABLE ROW LEVEL SECURITY;
ALTER TABLE themes DISABLE ROW LEVEL SECURITY; 